/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CsvByDateRouteImport } from './routes/csv/by-date'
import { Route as CsvByChartRouteImport } from './routes/csv/by-chart'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvByDateRoute = CsvByDateRouteImport.update({
  id: '/csv/by-date',
  path: '/csv/by-date',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvByChartRoute = CsvByChartRouteImport.update({
  id: '/csv/by-chart',
  path: '/csv/by-chart',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/csv/by-chart': typeof CsvByChartRoute
  '/csv/by-date': typeof CsvByDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/csv/by-chart': typeof CsvByChartRoute
  '/csv/by-date': typeof CsvByDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/upload': typeof UploadRoute
  '/csv/by-chart': typeof CsvByChartRoute
  '/csv/by-date': typeof CsvByDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/onboarding'
    | '/register'
    | '/upload'
    | '/csv/by-chart'
    | '/csv/by-date'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/onboarding'
    | '/register'
    | '/upload'
    | '/csv/by-chart'
    | '/csv/by-date'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/onboarding'
    | '/register'
    | '/upload'
    | '/csv/by-chart'
    | '/csv/by-date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  UploadRoute: typeof UploadRoute
  CsvByChartRoute: typeof CsvByChartRoute
  CsvByDateRoute: typeof CsvByDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv/by-date': {
      id: '/csv/by-date'
      path: '/csv/by-date'
      fullPath: '/csv/by-date'
      preLoaderRoute: typeof CsvByDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv/by-chart': {
      id: '/csv/by-chart'
      path: '/csv/by-chart'
      fullPath: '/csv/by-chart'
      preLoaderRoute: typeof CsvByChartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  UploadRoute: UploadRoute,
  CsvByChartRoute: CsvByChartRoute,
  CsvByDateRoute: CsvByDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
